name: Build Astre engine (Windows)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure and build
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_INSTALL_PREFIX=install -DASTRE_BUILD_TESTS=ON
        cmake --build build --config Debug --target install -j 4

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: astre-build
        path: |
          install

  tests:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Download test binary
      uses: actions/download-artifact@v4
      with:
        name: astre-build
        path: artifacts

    - name: Run tests
      run: |
        artifacts\bin\AstreEngineTests.exe --gtest_filter=-OpenGLShaderRealContextTest.*:WinapiProcessTest.RegisterUnregisterOGLContext
  
  package:
    runs-on: windows-latest
    needs: tests  # Only runs if tests pass

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: astre-build
        path: artifacts

    - name: Create zip package
      run: |
        Compress-Archive -Path artifacts\* -DestinationPath astre-engine.zip

    - name: Upload final packaged artifact
      uses: actions/upload-artifact@v4
      with:
        name: astre-engine
        path: astre-engine.zip
